// ── CV — Johann Glock ─────────────────────────────────────────────────────────
//
// Compiled by scripts/generate-pdf.ts via:
//   typst compile --font-path scripts/fonts scripts/cv.typ <output>
//
// Private contact injection (application variant):
//   typst compile --input email="..." --input phone="..." ...
//
// Data source: scripts/cv-data.json (generated by scripts/export-cv-data.ts)

#let data = json("cv-data.json")

// ── Private contact inputs ────────────────────────────────────────────────────

#let cv-email = sys.inputs.at("email", default: "")
#let cv-phone = sys.inputs.at("phone", default: "")

// ── Colors (indigo-light theme tokens) ───────────────────────────────────────
// oklch(lightness%, chroma, huedeg)

#let accent  = oklch(48.1%, 0.199, 281.9deg)
#let c-text  = oklch(22.8%, 0.038, 282.9deg)
#let c-head  = oklch(16.8%, 0.017, 284.5deg)
#let c-muted = oklch(48%,   0.051, 284.3deg)
#let c-bord  = oklch(85%,   0.01,  286deg)

// ── Page setup ────────────────────────────────────────────────────────────────

#set page(
  paper: "a4",
  margin: (top: 18mm, bottom: 18mm, left: 20mm, right: 20mm),
)

// ── Typography ────────────────────────────────────────────────────────────────

#set text(
  font: "Inter",
  size: 9.5pt,
  fill: c-text,
  lang: "en",
  kerning: true,
  ligatures: true,
  overhang: true,
)

#set par(
  justify: false,
  leading: 0.55em,
  spacing: 0.75em,
)

// Links: accent color, subtle underline
#show link: it => text(fill: accent)[#underline(
  stroke: accent.transparentize(65%),
  offset: 1.5pt,
  it
)]

// ── Helper: section heading ───────────────────────────────────────────────────

#let section-heading(title) = {
  v(18pt, weak: true)
  text(size: 9pt, weight: 700, tracking: 0.8pt, fill: accent, upper(title))
  v(-3pt)
  line(length: 100%, stroke: 0.75pt + c-bord)
  v(8pt, weak: true)
}

// ── Helper: subsection heading ────────────────────────────────────────────────

#let sub-heading(title) = {
  v(8pt, weak: true)
  block(spacing: 0pt, text(size: 8pt, weight: 700, tracking: 0.5pt, fill: c-muted, upper(title)))
  v(5pt)
}

// ── Helper: timeline entry (non-breaking, date col + body col) ────────────────

#let entry(date, body) = {
  block(breakable: false, width: 100%, spacing: 0pt, {
    grid(
      columns: (52pt, 1fr),
      column-gutter: 8pt,
      text(size: 8.5pt, fill: c-muted, date),
      body,
    )
  })
  v(16pt)
}

// ── Helper: tight bullet list ─────────────────────────────────────────────────

#let cv-bullets(items) = {
  v(1pt)
  list(
    indent: 4pt,
    body-indent: 4pt,
    spacing: 4pt,
    ..items.map(item => par(leading: 0.55em, text(size: 9pt)[#item]))
  )
}

// ── Helper: compact one-liner ─────────────────────────────────────────────────

#let compact-line(body) = {
  block(spacing: 0pt, body)
  v(6pt)
}

// ═════════════════════════════════════════════════════════════════════════════
// Document
// ═════════════════════════════════════════════════════════════════════════════

// ── Header ───────────────────────────────────────────────────────────────────

#grid(
  columns: (68pt, 1fr),
  column-gutter: 20pt,
  // Photo — clipped to circle
  box(
    clip: true,
    radius: 50%,
    width: 68pt,
    height: 68pt,
    image("../src/lib/assets/profile.png", width: 68pt, height: 68pt, fit: "cover"),
  ),
  // Name + meta
  {
    text(size: 20pt, weight: 800, tracking: -0.6pt, fill: c-head)[#data.profile.name]
    v(1pt)
    text(size: 10.5pt, fill: c-muted)[#data.profile.tagline]
    v(2pt)
    text(size: 8.5pt, fill: c-muted)[
      #link(data.profile.affiliationUrl)[#data.profile.affiliation]
      #h(3pt)·#h(3pt) Advisor: Prof. Martin Pinzger
      #h(3pt)·#h(3pt) Expected graduation: Q4 2026
    ]
    v(2pt)
    text(size: 8.5pt, fill: c-muted)[
      #link("https://glockyco.com")[glockyco.com]
      #h(3pt)·#h(3pt)
      #link(data.profile.github)[github.com/glockyco]
      #h(3pt)·#h(3pt)
      #link(data.profile.linkedin)[LinkedIn]
      #h(3pt)·#h(3pt)
      #link("https://orcid.org/" + data.profile.orcid)[ORCID]
    ]
    if cv-email != "" or cv-phone != "" {
      v(1pt)
      let parts = ()
      if cv-email != "" { parts.push(cv-email) }
      if cv-phone != "" { parts.push(cv-phone) }
      text(size: 8.5pt, fill: c-muted, parts.join([#h(3pt)·#h(3pt)]))
    }
  }
)

// ── Summary ───────────────────────────────────────────────────────────────────

#v(6pt)
#line(length: 100%, stroke: 1.5pt + accent)
#v(4pt)
#text(size: 9pt)[#data.researchSummary]
#v(8pt)

// ── Experience ────────────────────────────────────────────────────────────────

#section-heading("Experience")

#for job in data.workExperience {
  let date-str = if job.endYear == none {
    "since " + str(job.startYear)
  } else {
    str(job.startYear) + "–" + str(job.endYear)
  }
  entry(date-str, {
    text(weight: 600, fill: c-head)[#job.title]
    linebreak()
    text(size: 9pt, fill: c-muted)[#job.company · #job.location]
    if job.highlights.len() > 0 {
      cv-bullets(job.highlights)
    }
  })
}

// ── Education ─────────────────────────────────────────────────────────────────

#section-heading("Education")

#for edu in data.education {
  let date-str = if edu.endYear == none {
    "since " + str(edu.startYear)
  } else {
    str(edu.startYear) + "–" + str(edu.endYear)
  }
  entry(date-str, {
    text(weight: 600, fill: c-head)[#edu.degree in #edu.field]
    linebreak()
    text(size: 9pt, fill: c-muted)[#edu.institution · #edu.location]
    if edu.thesis != none {
      linebreak()
      text(size: 9pt)[Thesis: #emph(edu.thesis)]
    }
    if edu.theses != none {
      for t in edu.theses {
        linebreak()
        text(size: 9pt)[#t.label thesis: #emph(t.title)]
      }
    }
    if edu.advisor != none {
      linebreak()
      text(size: 9pt)[Advisor: #edu.advisor]
    }
    let extras = ()
    if edu.distinction != none { extras.push(edu.distinction) }
    if edu.scholarship != none { extras.push(edu.scholarship) }
    if edu.gpa != none { extras.push("GPA " + edu.gpa) }
    if extras.len() > 0 {
      linebreak()
      text(size: 9pt)[#extras.join(" · ")]
    }
  })
}

// ── Publications ──────────────────────────────────────────────────────────────

#pagebreak()
#section-heading("Publications")

#for (i, pub) in data.publications.enumerate() {
  block(breakable: false, spacing: 0pt, {
    par(leading: 0.6em, {
      [#(i + 1).\u{00A0}\u{00A0}]
      for (j, author) in pub.authors.enumerate() {
        if j > 0 { [, ] }
        if author.isMe { strong(author.name) } else { [#author.name] }
      }
      [. ]
      emph(pub.title)
      [. ]
      if pub.status == "under-review" {
        [Under review at #pub.venueShort.]
      } else {
        [#pub.venueDisplay, #pub.year.]
      }
      if pub.doi != none {
        [ DOI: #link("https://doi.org/" + pub.doi)[#pub.doi]]
      } else if pub.arxivId != none {
        [ arXiv: #link("https://arxiv.org/abs/" + pub.arxivId)[#pub.arxivId]]
      }
    })
  })
  v(10pt)
}

// ── Software Projects ─────────────────────────────────────────────────────────

#section-heading("Software Projects")

#for project in data.projects {
  block(spacing: 0pt, {
    link("https://glockyco.com/projects/" + project.slug + "/")[#text(weight: 600)[#project.title]]
    linebreak()
    text(size: 9pt, fill: c-muted)[#project.tagline]
    linebreak()
    text(size: 8.5pt, fill: c-muted, style: "italic")[#project.techStack.join(", ")]
  })
  v(10pt)
}

// ── Teaching & Supervision ────────────────────────────────────────────────────

#section-heading("Teaching & Supervision")

#sub-heading("Lab Instructor")
#for course in data.teaching.labInstructors {
  compact-line({
    text(weight: 600, fill: c-head)[#course.course]
    text(fill: c-muted)[
      #h(4pt)·#h(4pt)#course.institution#h(4pt)·#h(4pt)#course.semesterCount #if course.semesterCount == 1 { "semester" } else { "semesters" }
    ]
    if course.topics != none {
      linebreak()
      text(size: 8.5pt, fill: c-muted, style: "italic")[#course.topics]
    }
  })
}

#sub-heading("Tutor")
#for course in data.teaching.tutors {
  compact-line({
    text(weight: 600, fill: c-head)[#course.course]
    text(fill: c-muted)[
      #h(4pt)·#h(4pt)#course.institution#h(4pt)·#h(4pt)#course.semesterCount #if course.semesterCount == 1 { "semester" } else { "semesters" }
    ]
  })
}

#sub-heading("Supervision")
#let s = data.supervision
#text(fill: c-muted)[
  #s.mscTheses.total MSc #if s.mscTheses.total == 1 { "thesis" } else { "theses" },
  #s.mscProjects.total MSc #if s.mscProjects.total == 1 { "project" } else { "projects" },
  #s.bscTheses.total BSc #if s.bscTheses.total == 1 { "thesis" } else { "theses" },
  #s.bscInterns.total BSc interns,
  #s.hsInterns.total high-school interns
]

// ── Service & Outreach ────────────────────────────────────────────────────────

#section-heading("Service & Outreach")

#sub-heading("Peer Review")
#for item in data.service.reviewer {
  compact-line({
    text(weight: 600, fill: c-head)[Reviewer]
    text(fill: c-muted)[
      #h(4pt)·#h(4pt)#item.venue#if item.note != none [#h(4pt)·#h(4pt)#item.note]
    ]
  })
}
#compact-line({
  text(weight: 600, fill: c-head)[Sub-reviewer]
  text(fill: c-muted)[
    #h(4pt)·#h(4pt)#data.service.subreviewer.map(item =>
      item.venue + " " + str(item.year) + if item.count > 1 { " ×" + str(item.count) } else { "" }
    ).join(", ")
  ]
})

#sub-heading("Outreach")
#for item in data.service.outreach {
  compact-line({
    text(weight: 600, fill: c-head)[#item.venue]
    if item.note != none {
      text(fill: c-muted)[#h(4pt)·#h(4pt)#item.note]
    } else if item.year != none {
      text(fill: c-muted)[#h(4pt)·#h(4pt)#str(item.year)]
    }
  })
}

// ── Skills ────────────────────────────────────────────────────────────────────

#section-heading("Skills")

#for group in data.skills {
  sub-heading(group.category)
  block(spacing: 0pt, text(size: 9pt, fill: c-muted)[#group.items.join(", ")])
  v(6pt)
}
